import { defineApp } from "convex/server";
import { v } from "convex/values";
import kpiConvex from "@okrlinkhub/kpi-convex/convex.config";

const app = defineApp({
  env: {
    KPI_CONVEX_R2_ENDPOINT: v.string(),
    KPI_CONVEX_R2_BUCKET: v.string(),
    KPI_CONVEX_R2_ACCESS_KEY_ID: v.string(),
    KPI_CONVEX_R2_SECRET_ACCESS_KEY: v.string(),
    KPI_CONVEX_CATALOG_OBJECT_KEY: v.string(),
    KPI_CONVEX_SOURCE_KEY: v.string(),
    KPI_CONVEX_CATALOG_PREFIX: v.optional(v.string()),
    KPI_CONVEX_RELEASE_PUBLIC_KEYS_JSON: v.string(),
    KPI_CONVEX_SOURCE_PUBLIC_KEYS_JSON: v.string(),
    KPI_CONVEX_CLICKHOUSE_URL: v.string(),
    KPI_CONVEX_CLICKHOUSE_DATABASE: v.string(),
    KPI_CONVEX_CLICKHOUSE_USERNAME: v.string(),
    KPI_CONVEX_CLICKHOUSE_PASSWORD: v.string(),
    KPI_CONVEX_VALUES_READY_HMAC_SECRET: v.string(),
    KPI_CONVEX_SCOPE_VALUE: v.optional(v.string()),
    KPI_CONVEX_PROJECTED_POINTS: v.optional(v.string()),
    KPI_CONVEX_VIEWER_KEY_SALT: v.string(),
    KPI_EXAMPLE_ALLOW_ANONYMOUS: v.optional(v.string()),
  },
});

app.use(kpiConvex, {
  name: "kpiConvex",
  httpPrefix: "/kpi/",
  env: {
    KPI_CONVEX_R2_ENDPOINT: app.env.KPI_CONVEX_R2_ENDPOINT,
    KPI_CONVEX_R2_BUCKET: app.env.KPI_CONVEX_R2_BUCKET,
    KPI_CONVEX_R2_ACCESS_KEY_ID: app.env.KPI_CONVEX_R2_ACCESS_KEY_ID,
    KPI_CONVEX_R2_SECRET_ACCESS_KEY: app.env.KPI_CONVEX_R2_SECRET_ACCESS_KEY,
    KPI_CONVEX_CATALOG_OBJECT_KEY: app.env.KPI_CONVEX_CATALOG_OBJECT_KEY,
    KPI_CONVEX_CATALOG_PREFIX: app.env.KPI_CONVEX_CATALOG_PREFIX,
    KPI_CONVEX_SOURCE_KEY: app.env.KPI_CONVEX_SOURCE_KEY,
    KPI_CONVEX_RELEASE_PUBLIC_KEYS_JSON:
      app.env.KPI_CONVEX_RELEASE_PUBLIC_KEYS_JSON,
    KPI_CONVEX_SOURCE_PUBLIC_KEYS_JSON:
      app.env.KPI_CONVEX_SOURCE_PUBLIC_KEYS_JSON,
    KPI_CONVEX_CLICKHOUSE_URL: app.env.KPI_CONVEX_CLICKHOUSE_URL,
    KPI_CONVEX_CLICKHOUSE_DATABASE: app.env.KPI_CONVEX_CLICKHOUSE_DATABASE,
    KPI_CONVEX_CLICKHOUSE_USERNAME: app.env.KPI_CONVEX_CLICKHOUSE_USERNAME,
    KPI_CONVEX_CLICKHOUSE_PASSWORD: app.env.KPI_CONVEX_CLICKHOUSE_PASSWORD,
    KPI_CONVEX_VALUES_READY_HMAC_SECRET:
      app.env.KPI_CONVEX_VALUES_READY_HMAC_SECRET,
    KPI_CONVEX_SCOPE_VALUE: app.env.KPI_CONVEX_SCOPE_VALUE,
    KPI_CONVEX_PROJECTED_POINTS: app.env.KPI_CONVEX_PROJECTED_POINTS,
  },
});
export default app;
